name = "guestbook-hourly-sync"
main = "src/index.ts"
compatibility_date = "2026-07-12"
workers_dev = true

[triggers]
crons = ["0 * * * *"]

[vars]
GUESTBOOK_APP_URL = "https://guestbook.up.railway.app"
