ALTER TABLE guest_tags
ADD COLUMN IF NOT EXISTS semantic_key TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS guest_tags_semantic_key_key
ON guest_tags (semantic_key);

UPDATE guest_tags
SET semantic_key = 'referral'
WHERE semantic_key IS NULL
  AND LOWER(name) = LOWER('💎 Referred');

CREATE TABLE IF NOT EXISTS manual_tag_mutations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id TEXT NOT NULL REFERENCES luma_people(person_id) ON DELETE CASCADE,
  tag_id TEXT NOT NULL REFERENCES guest_tags(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ,
  assigned_event_id TEXT REFERENCES luma_events(event_id) ON DELETE SET NULL,
  removed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS manual_tag_mutations_person_tag_time_idx
ON manual_tag_mutations (person_id, tag_id, assigned_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS manual_tag_mutations_event_tag_time_idx
ON manual_tag_mutations (assigned_event_id, tag_id, assigned_at DESC);

CREATE INDEX IF NOT EXISTS manual_tag_mutations_tag_time_idx
ON manual_tag_mutations (tag_id, assigned_at DESC);

INSERT INTO manual_tag_mutations (
  person_id,
  tag_id,
  assigned_at,
  assigned_event_id,
  removed
)
SELECT
  person.person_id,
  definition.id,
  NULL,
  NULL,
  FALSE
FROM luma_people AS person
CROSS JOIN LATERAL jsonb_array_elements_text(
  CASE WHEN jsonb_typeof(person.manual_tags) = 'array' THEN person.manual_tags ELSE '[]'::jsonb END
) AS manual_tag(name)
JOIN guest_tags AS definition ON LOWER(definition.name) = LOWER(manual_tag.name)
WHERE NOT EXISTS (
  SELECT 1
  FROM manual_tag_mutations AS existing
  WHERE existing.person_id = person.person_id
    AND existing.tag_id = definition.id
);
